### PR TITLE
Migrate from Travis CI to GitHub Actions

### PR DESCRIPTION
**Pull request by AlexandrePicosson**
## Description

This PR adds a GitHub actions workflow to test and publish the package.

For the publication of the package I followed this documentation: https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/.

Someone with elevated permissions on this repo must create a secret `PYPI_API_TOKEN` containing an API key for pypi.
Link for api token creation https://pypi.org/manage/account/#api-tokens, note that the token must be created by an organisation account to ensure that it will not be deleted if the contributor that created it leave. 

## Motivation and Context

We switch from TravisCI to GH Actions due to the fact that https://travis-ci.org/ will close at the end of december ([source](https://docs.travis-ci.com/user/migrate/open-source-repository-migration#q-when-will-the-migration-from-travis-ciorg-to-travis-cicom-be-completed)).

## How Has This Been Tested?

You can look at the [Checks](https://github.com/SubstraFoundation/substra/pull/251/checks) tab to see the workflow logs.

Links:
- [Python pipeline](https://github.com/SubstraFoundation/substra/actions/runs/430526140)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by jmorel** [comment]
I believe the secret token can only be added by admins, so it'd be @samlesu or @camillemarini I think.

**Review by jmorel — CHANGES_REQUESTED** [review]
Thanks a lot Alexandre for the change. Let's wait for the token to be setup before merging though.

**Comment by inalgnu** [comment]
@jmorel @AlexandrePicosson the secret is created

**Comment by Kelvin-M** [comment]
@AlexandrePicosson Is there any reason to not setup a TestPyPI token + flow as suggested [here](https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#saving-credentials-on-github) and [there](https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#publishing-the-distribution-to-pypi-and-testpypi)

**Comment by AlexandrePicosson** [comment]
> @AlexandrePicosson Is there any reason to not setup a TestPyPI token + flow as suggested [here](https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#saving-credentials-on-github) and [there](https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#publishing-the-distribution-to-pypi-and-testpypi)

There is no particular reason, I just copied the flow we had with Travis, and there was no TestPypi before.

**Review by jmorel — APPROVED** [review]

**Pull request merged**
