### PR TITLE
Update helm release urls

### LINKED ISSUE #233: Broken links for helm hub in compatibility table
Links for helm releases in the compatibility table are ending in 404. It seems that helm hub is now redirected to artifacthub.io. We can find substra helm releases here: https://artifacthub.io/packages/search?page=1&ts_query_web=substra

### PR DESCRIPTION
**Pull request by natct10**
If this new domain appears to be legit, I have updated the links for helm releases which seems to be now hosted [here](https://artifacthub.io/packages/helm/substra/hlf-k8s/3.0.1) in the compatibility table.
Close #233

### CODE REVIEW

**Comment by natct10** [comment]
The redirections from hub.helm.sh to artifacthub.io seems to be working, shall I close this one or would you prefer to directly use artifacthub.io url?

**Comment by Kelvin-M** [comment]
I think it's better to have artifiacthub.io urls ! Can you rebase and update your PR ?

**Comment by natct10** [comment]
> I think it's better to have artifiacthub.io urls ! Can you rebase and update your PR ?

Done!

**Review by Kelvin-M — DISMISSED** [review]

**Review by jmorel — APPROVED** [review]

**Comment by Kelvin-M** [comment]
@natct10 Can you rebase this branch in order to merge it :) ?

**Comment by natct10** [comment]
> @natct10 Can you rebase this branch in order to merge it :) ?

Done, but I don't know why there is such a diff (I expected to only have the updated urls). Would you kindly have a quick look @Kelvin-M?

**Comment by Kelvin-M** [comment]
@natct10  this is the case no : https://github.com/SubstraFoundation/substra/pull/234/files ?

**Review by Kelvin-M — APPROVED** [review]

**Comment by natct10** [comment]
Is it okay to merge or more approvals are required? And if so, shall I merge myself?

**Review by Esadruhn — APPROVED** [review]
Thanks for the change ! One approval by a code owner is enough
You can merge yourself, use the squash and merge please

**Pull request merged**
