### PR TITLE
Remove run-local command

### PR DESCRIPTION
**Pull request by jmorel**
The debug mode that was introduced a few months ago covers more cases and allows for easier debugging than the run_local command.

This branch removes the run_local command and its documentation and updates the titanic example to mention the existence of the debug mode.

### CODE REVIEW

**Comment by Esadruhn** [comment]
Seems good on the substra repo ! It needs a companion PR on the docs:
-  https://doc.substra.ai/setup/demo.html#adding-your-learning-algorithm
- https://doc.substra.ai/setup/demo.html#resources

**Comment by natct10** [comment]
> Seems good on the substra repo ! It needs a companion PR on the docs:
> 
>     * https://doc.substra.ai/setup/demo.html#adding-your-learning-algorithm
> 
>     * https://doc.substra.ai/setup/demo.html#resources

Hi, is it going to be merged soon? 
I think it could be nice to keep the reference to the `run -local` mode as version 0.6 is still being used, but to add a note about this and remove it when the 0.7.* version is more broadly adopted.
Does this sound okay for you?

**Comment by jmorel** [comment]
Yes, it sounds perfect, I'll create the companion PR in the doc.

**Comment by jmorel** [comment]
Done, I did it in a way that can be merged without having to wait for the change in substra to be merged.

**Review by Esadruhn — APPROVED** [review]

**Pull request merged**
